accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts.views import ChangePasswordView, LoginView, RegisterView
from customers.views import search_customer_by_nif

app_name = 'accounts'
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/', ChangePasswordView.as_view(), name='password_change'),
    path('search_customer/', search_customer_by_nif, name='search_customer'),
]

setup/urls.py
# Custom error handlers
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('accounts.urls')),
    path('tickets/', include('tickets.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
import re

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core import validators
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from accounts.managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        _('username'),
        max_length=5,
        unique=True,
        help_text=_('Required. 5 characters or fewer. Letters and digits.'),
        validators=[
            validators.RegexValidator(re.compile(r'^[A-Za-z][A-Za-z0-9]*$'), _('Enter a valid username.'), _('invalid'))
        ],
        error_messages={
            'unique': _('A user with that username already exists.'),
        },
    )
    first_name = models.CharField(_('first name'), max_length=45, blank=True)
    last_name = models.CharField(_('last name'), max_length=45, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    vat_number = models.CharField(
        _('vat number'),
        max_length=20,
        blank=True,
        help_text=_('VAT number of the user.'),
    )

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email', 'vat_number']

    objects = CustomUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        """Return string representation of the user."""
        full_name = self.get_full_name()
        if full_name:
            return full_name
        return self.username

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms/login_form.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.utils.translation import gettext_lazy as _


class LoginForm(AuthenticationForm):
    username = UsernameField(
        label=_('Username'),
        widget=forms.TextInput(
            attrs={
                'autofocus': True,
                'autocomplete': 'off',
                'class': 'form-control',
                'placeholder': 'Entre seu utilizador',
            }
        ),
    )

    password = forms.CharField(
        label=_('Password'),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'current-password',
                'placeholder': 'Entre a palavra-passe',
                'class': 'form-control',
            }
        ),
    )

accounts/forms/password_change_form.py
# forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UsernameField
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from accounts.models import CustomUser


class ChangePasswordForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
        'invalid_username': _('This username is already taken.'),
    }

    user_name = UsernameField(
        label=_('Username'),
        widget=forms.TextInput(
            attrs={
                'autofocus': True,
                'autocomplete': 'off',
                'class': 'form-control',
                'placeholder': 'Entre seu utilizador',
            }
        ),
    )

    new_password1 = forms.CharField(
        label=_('Password'),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'placeholder': 'Entre a palavra-passe',
                'class': 'form-control',
            }
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )

    new_password2 = forms.CharField(
        label=_('Password confirmation'),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'placeholder': 'Entre a palavra-passe',
                'class': 'form-control',
            }
        ),
        help_text=_('Enter the same password as before, for verification.'),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    user_cache = None

    class Meta:
        model = CustomUser
        fields = ('user_name', 'new_password1', 'new_password2')

    def clean(self):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')

        if new_password1 and new_password2 and new_password1 != new_password2:
            self.add_error(
                'new_password2',
                ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                ),
            )

        # Validação adicional de força da senha
        try:
            if self.user_cache and new_password1:
                validate_password(new_password1, self.user_cache)
        except ValidationError as e:
            self.add_error(
                'new_password1',
                ValidationError(
                    str(e),
                    code='password_too_weak',
                ),
            )

        return super().clean()

    def clean_user_name(self):
        username = self.cleaned_data.get('user_name')

        self.user_cache = CustomUser.objects.filter(username__iexact=username).first()

        if not self.user_cache:
            self.add_error(
                'user_name',
                ValidationError(
                    self.error_messages['invalid_username'],
                    code='invalid_username',
                ),
            )

        return username

    def save(self, user):
        if user:
            password = self.cleaned_data['new_password1']
            user.set_password(password)  # Faz o hash automaticamente
            user.save()
            return user

        return None

accounts/forms/register_form.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.utils.translation import gettext_lazy as _

from accounts.models import CustomUser


class RegisterForm(UserCreationForm):
    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
    }

    vat_number = forms.CharField(
        max_length=20,
        required=True,
        label=_('VAT Number'),
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Informe o número de contribuinte',
                'autocomplete': 'off',
            }
        ),
    )

    password1 = forms.CharField(
        label=_('Password'),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'placeholder': 'Entre a palavra-passe',
                'class': 'form-control',
            }
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )

    password2 = forms.CharField(
        label=_('Password confirmation'),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'placeholder': 'Entre a palavra-passe',
                'class': 'form-control',
            }
        ),
        help_text=_('Enter the same password as before, for verification.'),
    )

    first_name = forms.CharField(
        max_length=45,
        required=True,
        label=_('Name'),
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    last_name = forms.CharField(
        max_length=45,
        required=True,
        label=_('Surname'),
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    email = forms.EmailField(
        max_length=254,
        required=True,
        label=_('Email'),
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
    )

    username = UsernameField(
        max_length=5,
        required=True,
        label=_('Username'),
        widget=forms.TextInput(
            attrs={
                'autofocus': True,
                'autocomplete': 'off',
                'class': 'form-control',
                'placeholder': 'Entre seu utilizador',
            }
        ),
        help_text=_('Required. Username must be between 3 and 5 characters long'),
    )

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'vat_number', 'password1', 'password2')

    # def clean_username(self):
    #     username = self.cleaned_data.get('username')
    #     if len(username) < 3 or len(username) > 5:  # noqa: PLR2004
    #         raise forms.ValidationError('Username must be between 3 and 5 characters long')
    #     return username

    def save(self, commit=True):
        user = super().save(commit=False)

        user.vat_number = user.vat_number.upper()
        user.username = user.username.upper()

        if commit:
            user.save()

        return user

accounts/views/login_view.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.views.generic import View

from accounts.forms import LoginForm


class LoginView(View):
    template_name = 'accounts/login.html'

    def get(self, request):
        data = {'form': LoginForm, 'error': None}
        return render(request, self.template_name, data)

    def post(self, request):
        data = LoginForm(request.POST or None)

        if data is not None:
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                # Check if the user is active
                if user.is_active:
                    # Log the user in
                    login(request, user)
                    return redirect('tickets:ticket_list')

        return render(
            request,
            self.template_name,
            {
                'form': data,
                'error': 'A autenticação falhou. Verifique o login, a senha e tente novamente.',
            },
        )

accounts/views/password_change_view.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import View

from accounts.forms import ChangePasswordForm
from accounts.models import CustomUser


class ChangePasswordView(View):
    template_name = 'accounts/password_change.html'

    def get(self, request):
        form = ChangePasswordForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ChangePasswordForm(request.POST)

        if form.is_valid():
            print('Formulário válido, processando...')
            try:
                user = form.cleaned_data.get('user_name')
                custom_user = CustomUser.objects.get(username=user)

                user = form.save(custom_user)

                if user:
                    return redirect('accounts:login')
                else:
                    print('Erro inesperado ao criar o usuário.')
                    messages.error(request, 'Ocorreu um erro inesperado ao criar o usuário.')
            except Exception as e:
                print(f'Erro durante o registro: {e}')
                messages.error(request, f'Erro durante o registro: {e}')
                # Logar 'e'
        else:
            print('Por favor, corrija os erros no formulário.')
            messages.error(request, 'Por favor, corrija os erros no formulário.')

        # Renderiza novamente em caso de erro no try ou form inválido
        return render(request, self.template_name, {'form': form})

accounts/views/register_view.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import View

from accounts.forms import RegisterForm
from profiles.models import UserProfile


class RegisterView(View):
    template_name = 'accounts/register.html'

    def get(self, request):
        form = RegisterForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)

        if form.is_valid():
            try:
                user = form.save()

                if user:
                    UserProfile.objects.create(user=user)
                    messages.success(request, 'Registro realizado com sucesso! Faça o login.')
                    return redirect('accounts:login')
                else:
                    messages.error(request, 'Ocorreu um erro inesperado ao criar o usuário.')
            except Exception as e:
                messages.error(request, f'Erro durante o registro: {e}')
                # Logar 'e'
        else:
            messages.error(request, 'Por favor, corrija os erros no formulário.')

        # Renderiza novamente em caso de erro no try ou form inválido
        return render(request, self.template_name, {'form': form})

accounts/templates/accounts/login.html
{% extends "core/base.html" %}<!-- HTML head meta tags, fonts and title tag -->
{% load static %}

{% block content %}
<div class="app-wrapper happy d-block">
  <div class="">
    <!-- Body main section starts -->
    <main class="w-100">
      <!-- sign in start -->
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-7 col-xl-8 d-none d-lg-block p-0">
            <div class="image-contentbox gs-bg-color-5">
              <img src={% static "/images/login/login_01.jpg" %} class="img-fluid" alt="">
            </div>
          </div>
          <div class="col-lg-5 col-xl-4 p-0 bg-white">
            <div class="form-container">
              <form class="app-form" method="post">
                <div class="row">
                  <div class="col-12">
                    <div class="mb-5 text-center text-lg-start">
                      <h2 class="text-primary f-w-600">Bem-vindo ao GSC Service </h2>
                      <p>Entre com os dados que introduziu durante o seu registo</p>
  
                      {% if error %}
                        <div class="form-text text-danger py-3">
                          {{ error }}
                        </div>
                      {% endif %}
                    </div>
                  </div>
                </div>
                {% csrf_token %}

                <div class="row">
                  <div class="col-12">
                    <div class="mb-3">
                      <label for="username" class="form-label">{{ form.username.label }}</label>
                      {{ form.username }}
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="mb-3">
                      <label for="password" class="form-label">{{ form.password.label }}</label>
                      {{ form.password }}
                    </div>
                  </div>
                  <div class="col-6">
                    <div class="form-check mb-3">
                      <input class="form-check-input" type="checkbox" value="" id="checkDefault">
                      <label class="form-check-label text-secondary" for="checkDefault">
                        Remember me
                      </label>
                    </div>
                  </div>
                  <div class="col-6">
                    <div class="mb-3">
                      <a href="{% url 'accounts:password_change' %}" class="link-primary float-end">Esqueci a password</a>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="mb-3">
                      <!--a href="./index" role="button" class="btn btn-primary w-100">Sign In</a-->
                      <input type="submit" class="btn btn-primary w-100" value="Login">
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="text-center text-lg-start">
                      Ainda não tem uma conta? <a href="{% url 'accounts:register' %}"
                        class="link-primary text-decoration-underline"> Criar nova conta</a>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- sign in end -->
    </main>
    <!-- Body main section ends -->
  </div>
</div>
{% include "core/partials/scriptsAuth.html" %}
{% endblock content %}

accounts/templates/accounts/password_change.html
{% extends "core/base.html" %}<!-- HTML head meta tags, fonts and title tag -->
{% load static %}

{% block content %}
  <div class="app-wrapper happy d-block">
    <div class="">
      <!-- Body main section starts -->
      <!-- Reset Your Password start -->
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-7 col-xl-8 d-none d-lg-block p-0">
            <div class="image-contentbox">
              <img src={% static "/images/login/03.png" %} class="img-fluid" alt="">
            </div>
          </div>
          <div class="col-lg-5 col-xl-4 p-0 bg-white">
            <div class="form-container">
              <!--{% if messages %}
                <ul class="messages">
                  {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                  {% endfor %}
                </ul>
              {% endif %}-->
              <form class="app-form" method="post" action=".">
                <div class="row">
                  <div class="col-12">
                    <div class="mb-5 text-center text-lg-start">
                      <h2 class="text-primary f-w-600">Redefinir a sua palavra-passe</h2>
                      <p>Crie uma nova palavra-passe e faça login</p>
                    </div>
                  </div>
                  {% csrf_token %}

                  {% for field in form %}
                    <div class="col-12">
                      <div class="mb-3">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.errors %}
                          <div class="text-danger">{{ field.errors }}</div>
                        {% endif %}

                        {% if field.help_text %}
                          <div class="mt-3">
                            <small class="text-info">{{ field.help_text }}</small>
                          </div>
                        {% endif %}
                      </div>
                    </div>
                  {% endfor %}
                  <div class="col-12">
                    <div class="mb-3">
                      <input type="submit" class="btn btn-primary w-100" value="Registar">
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- Reset Your Password end -->
      <!-- Body main section ends -->
    </div>
  </div>
  {% include "core/partials/scriptsAuth.html" %}
{% endblock content %}

accounts/templates/accounts/password_reset_set.html
<h2>Redefinir Senha - Passo 2</h2>
<p>Por favor, defina sua nova senha.</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Redefinir Senha</button>
</form>

accounts/templates/accounts/register.html
{% extends "core/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<div class="app-wrapper happy">

  {% include "core/partials/preloader.html" %}

  <!-- Menu Navigation starts -->
  {% include "core/partials/navbar.html" %}
  <!-- Menu Navigation ends -->

  <div class="app-content">
    <div class="">

      <!-- Header Section starts -->
      {% include "core/partials/header.html" %}
      <!-- Header Section ends -->

      <!-- Body main section starts -->
      <main>
        <div class="container-fluid">
          <!-- Form With Separator start -->
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h5>Crie sua conta</h5>
              </div>
              <div class="card-body">
                <form class="app-form" method="post">
                  {% csrf_token %}

                  <div class="row">
                    <div class="col-12">
                      <h5 class="mb-3">Identificação</h5>
                    </div>
                    <div class="col-6">
                      <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">{{ form.username.label }}</label>
                        {{ form.username }}
                        {% if form.username.help_text %}
                          <div class="mt-3">
                            <small class="text-info">{{ form.username.help_text }}</small>
                          </div>
                        {% endif %}
                        {% if form.username.errors %}
                          <div class="mt-3">
                            <small class="text-danger">{{ form.username.errors }}</small>
                          </div>
                        {% endif %}
                      </div>
                    </div>
                    <div class="col-6">
                      <div class="mb-3">
                        <label for="{{ form.email.id_for_label }}" class="form-label">{{ form.email.label }}</label>
                        {{ form.email }}
                        {% if form.email.help_text %}
                          <div class="mt-3">
                            <small class="text-info">{{ form.email.help_text }}</small>
                          </div>
                        {% endif %}
                        {% if form.email.errors %}
                          <div class="mt-3">
                            <small class="text-danger">{{ form.email.errors }}</small>
                          </div>
                        {% endif %}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="mb-3">
                        <label for="{{ form.first_name.id_for_label }}" class="form-label">{{ form.first_name.label }}</label>
                        {{ form.first_name }}
                        {% if form.first_name.help_text %}
                          <div class="mt-3">
                            <small class="text-info">{{ form.first_name.help_text }}</small>
                          </div>
                        {% endif %}
                        {% if form.first_name.errors %}
                          <div class="mt-3">
                            <small class="text-danger">{{ form.first_name.errors }}</small>
                          </div>
                        {% endif %}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="mb-3">
                        <label for="{{ form.last_name.id_for_label }}" class="form-label">{{ form.last_name.label }}</label>
                        {{ form.last_name }}
                        {% if form.last_name.help_text %}
                          <div class="mt-3">
                            <small class="text-info">{{ form.last_name.help_text }}</small>
                          </div>
                        {% endif %}
                        {% if form.last_name.errors %}
                          <div class="mt-3">
                            <small class="text-danger">{{ form.last_name.errors }}</small>
                          </div>
                        {% endif %}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="mb-3">
                        <label for="{{ form.first_name.id_for_label }}" class="form-label">{{ form.password1.label }}</label>
                        {{ form.password1 }}
                        {% if form.password1.help_text %}
                          <div class="mt-3">
                            <small class="text-info">{{ form.password1.help_text }}</small>
                          </div>
                        {% endif %}
                        {% if form.password1.errors %}
                          <div class="mt-3">
                            <small class="text-danger">{{ form.password1.errors }}</small>
                          </div>
                        {% endif %}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="mb-3">
                        <label for="{{ form.password2.id_for_label }}" class="form-label">{{ form.password2.label }}</label>
                        {{ form.password2 }}
                        {% if form.password2.help_text %}
                          <div class="mt-3">
                            <small class="text-info">{{ form.password2.help_text }}</small>
                          </div>
                        {% endif %}
                        {% if form.password2.errors %}
                          <div class="mt-3">
                            <small class="text-danger">{{ form.password2.errors }}</small>
                          </div>
                        {% endif %}
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="app-divider-v dotted"></div>
                    </div>
                    <div class="col-12">
                      <h5 class="mb-3">Organização</h5>
                    </div>
                      
                    <div class="col-6">
                      <div class="mb-3">
                        <label for="{{ form.vat_number.id_for_label }}" class="form-label">{{ form.vat_number.label }}</label>
                        <input name="vat_number" autocomplete="off" class="form-control text-uppercase" hx-get="{% url 'accounts:search_customer' %}" hx-trigger="keyup changed delay:500ms" hx-target="#customer-name" hx-swap="innerHTML" />
                        {% if form.vat_number.help_text %}
                          <div class="mt-3">
                            <small class="text-info">{{ form.vat_number.help_text }}</small>
                          </div>
                        {% endif %}
                        {% if form.vat_number.errors %}
                          <div class="mt-3">
                            <small class="text-danger">{{ form.vat_number.errors }}</small>
                          </div>
                        {% endif %}
                      </div>
                    </div>
                    <div class="col-6">
                      <div class="mb-3">
                        <label class="form-label">Empresa</label>
                        {% include 'accounts/partials/search_customer.html' %}
                      </div>
                    </div>
                    <div class="col-6">
                      <div class="text-start">
                        Já possui uma conta? <a href="{% url 'accounts:login' %}" class="link-primary text-text-decoration-underline"> Login</a>
                      </div>
                    </div>
                    <div class="col-6">
                      <div class="text-end">
                        <button type="submit" class="btn btn-primary">Registar</button>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <!-- Form With Separator end -->
        </div>
        <!-- default forms end -->
      </div>
    </main>

    <!-- Body main section ends -->

  </div>
</div>

</div>

<!-- tap on top -->
<div class="go-top">
<span class="progress-value">
  <i class="ti ti-arrow-up"></i>
</span>
</div>

<!-- essential -->

<!--customizer-->
{% include "core/partials/customizer.html" %}

{% include "core/partials/scripts.html" %}    

{% include "core/partials/scripts2.html" %}

{% endblock content %}