accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts.views import ChangePasswordView, LoginView, RegisterView
from customers.views import search_customer_by_nif

app_name = 'accounts'
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/', ChangePasswordView.as_view(), name='password_change'),
    path('search_customer/', search_customer_by_nif, name='search_customer'),
]

setup/urls.py
# Custom error handlers
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('accounts.urls')),
    path('tickets/', include('tickets.urls')),
    path('admin/', admin.site.urls),
]

tickets/urls.py
from django.urls import path

from tickets.views import TicketListView, page_not_found_view

app_name = 'tickets'
urlpatterns = [
    path('list/', TicketListView.as_view(), name='ticket_list'),
    path('not-found/', page_not_found_view, name='page_not_found'),
]

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/base.html')

core/templates/core/partials/customizer.html
{% load static %}
<div id="customizer"></div>

core/templates/core/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"
    content="Multipurpose, super flexible, powerful, clean modern responsive bootstrap 5 admin template">
  <meta name="keywords"
    content="admin template, AdminX admin template, dashboard template, flat admin template, responsive admin template, web app">
  <meta name="author" content="Arteam">
  <link rel="icon" href={% static "/images/logo/favicon.png" %} type="image/x-icon">
  <link rel="shortcut icon" href={% static "/images/logo/favicon.png" %} type="image/x-icon">

  <title>GSConsulting - Service Desk X3</title>

  <!-- HTMX-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/htmx/2.0.4/htmx.min.js" integrity="sha512-2kIcAizYXhIn8TzUvqzEDZNuDZ+aW7yE/+f1HJHXFjQcGNfv1kqzJSTBRBSlOgp6B/KZsz1K0a3ZTqP9dnxioQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <!--font-awesome-css-->
  <link rel="stylesheet" href={% static "/vendor/fontawesome/css/all.css" %}>

  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

core/templates/core/partials/head2.html
  {% load static %}
  <!-- tabler icons-->
  <link rel="stylesheet" type="text/css" href={% static "/vendor/tabler-icons/tabler-icons.css" %}>

  <!--flag Icon css-->
  <link rel="stylesheet" type="text/css" href={% static "/vendor/flag-icons-master/flag-icon.css" %}>

  <!-- Data Table css-->
  <link rel="stylesheet" type="text/css" href="{% static '/vendor/datatable/jquery.dataTables.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/vendor/datatable/datatable2/buttons.dataTables.min.css' %}">

core/templates/core/partials/head3.html
{% load static %}
  <!-- Bootstrap css-->
  <link rel="stylesheet" type="text/css" href={% static "/vendor/bootstrap/bootstrap.min.css" %}>

  <!-- simplebar css-->
  <link rel="stylesheet" type="text/css" href={% static "/vendor/simplebar/simplebar.css" %}>

  <!-- App css-->
  <link rel="stylesheet" type="text/css" href={% static "/css/style.css" %}>

  <!-- Responsive css-->
  <link rel="stylesheet" type="text/css" href={% static "/css/responsive.css" %}>
  
  <!-- Custom css files-->
  <link rel="stylesheet" type="text/css" href={% static "css/gsc.css" %}>

  </head>

<body class="ltr" text="small-text">

core/templates/core/partials/header.html
{% load static %}
<!-- Header Section starts -->
<header class="header-main">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-12 d-flex align-items-center justify-content-end header-right">
                <ul class="d-flex align-items-center">
                  <li class="header-language">
                    <div id="lang_selector" class="flex-shrink-0 dropdown">
                      <a href="#" class="d-block head-icon ps-0" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <div class="lang-flag lang-en ">
                          <span class="flag rounded-circle overflow-hidden">
                            <i class="flag-icon flag-icon-prt flag-icon-squared b-r-50 f-s-22"></i>
                          </span>
                        </div>
                      </a>
                      <ul class="dropdown-menu language-dropdown dropdown-menu-end header-card border-0 p-0">
                        <li>
                          <div class="card-header bg-dark py-2">
                            <h5 class="text-white">language <span class="float-end"><i
                                  class="ti ti-language"></i></span></h5>
                          </div>
                        </li>
                        <li class="lang lang-pt selected dropdown-item p-2" title="PT">
                          <span class="d-flex align-items-center">
                            <i class="flag-icon flag-icon-prt flag-icon-squared b-r-50 f-s-22"></i>
                            <span class="ps-2 text-secondary">Português</span>
                          </span>
                        </li>
                        <li class="lang lang-en selected dropdown-item p-2" title="US">
                          <span class="d-flex align-items-center">
                            <i class="flag-icon flag-icon-usa flag-icon-squared b-r-50 f-s-22"></i>
                            <span class="ps-2 text-secondary">Inglês</span>
                          </span>
                        </li>
                        <li class="lang lang-pt dropdown-item p-2" title="FR">
                          <span class="d-flex align-items-center">
                            <i class="flag-icon flag-icon-fra flag-icon-squared b-r-50 f-s-22"></i>
                            <span class="ps-2 text-secondary">Frances</span>
                          </span>
                        </li>
                        <li class="lang lang-es dropdown-item p-2" title="UK">
                          <span class="d-flex align-items-center">
                            <i class="flag-icon flag-icon-gbr flag-icon-squared b-r-50 f-s-22"></i>
                            <span class="ps-2 text-secondary">Inglês - UK</span>
                          </span>
                        </li>
                      </ul>
                    </div>
                  </li>
                  <!-- Header profile-->
                  <li class="header-profile">
                    <div class="flex-shrink-0 dropdown">
                      <a href="#" class="d-block head-icon pe-0" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <img src={% static "/images/avatar/avatar.png" %} alt="mdo" class="rounded-circle h-35 w-35">
                      </a>
                      <ul class="dropdown-menu dropdown-menu-end header-card border-0 px-2">
                        <li class="dropdown-item d-flex align-items-center p-2">
                          <span class="h-35 w-35 d-flex-center b-r-50 position-relative">
                            <img src={% static "/images/avatar/avatar.png" %} alt="" class="img-fluid b-r-50">
                            <span
                              class="position-absolute top-0 end-0 p-1 bg-success border border-light rounded-circle animate__animated animate__fadeIn animate__infinite animate__fast"></span>
                          </span>
                          <div class="flex-grow-1 ps-2">
                            <h6 class="mb-0"> {{ user }}</h6>
                            <p class="f-s-12 mb-0 text-secondary">{{ company_name }}</p>
                          </div>
                        </li>
                        <li class="app-divider-v dotted my-1"></li>
                        <li>
                          <a class="dropdown-item" href="{% url 'tickets:page_not_found' %}">
                            <i class="ti ti-user-circle pe-1 f-s-18"></i> Profile
                          </a>
                        </li>
                        <li class="app-divider-v dotted my-1"></li>
                        <li class="btn-light-danger b-r-5">
                          <form method="post" action="{% url 'accounts:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="dropdown-item mb-0 text-danger">
                              <i class="ti ti-logout pe-1 f-s-18 text-danger"></i>
                              Logout
                            </button>
                          </form>
                        </li>
                      </ul>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Header Section ends -->

core/templates/core/partials/navbar.html
{% load static %}

<nav class="dark-sidebar">
  <div class="app-logo">
    <a class="logo d-inline-block" href="#">
      <img src={% static "/gsc/logo_gsc.png" %} alt="#" class="dark-logo">
    </a>

    <span class="bg-light-light toggle-semi-nav">
      <i class="ti ti-chevrons-right f-s-20"></i>
    </span>
  </div>
  <div class="app-nav" id="app-simple-bar" data-simplebar="init">
    <ul class="main-nav p-0 mt-2">
      <li class="menu-title"> <span>Dashboard</span></li>

      <li>
        <a class="show" data-bs-toggle="collapse" href="#dashboard" aria-expanded="false">
          <i class="ti ti-home"></i>
          dashboard
          <span class="badge text-bg-primary badge-notification ms-2">2</span>
        </a>
        <ul class="collapse show" id="dashboard" aria-expanded="true">
          <li><a href="#">Em construção</a></li>
          <li><a href="#">Em construção</a></li>
        </ul>
      </li>

      <li class="menu-title"> <span>Suporte</span></li>

      <li class="no-sub">
        <a class="" href="#">
          <i class="ti ti-headset"></i> Tickets
        </a>
      </li>

    </ul>
  </div>
</nav>

core/templates/core/partials/preloader.html
    <div class="loader-wrapper">
      <div class="app-loader">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

core/templates/core/partials/scripts.html
{% load static %}
<!-- latest jquery-->
<script src={% static "/js/jquery-3.6.3.min.js" %}></script>

<!-- Bootstrap js-->
<script src={% static "/vendor/bootstrap/bootstrap.bundle.min.js" %}></script>

<!-- Simple bar js-->
<script src={% static "/vendor/simplebar/simplebar.js" %}></script>

<!-- Customizer js-->
<script src={% static "js/customizer.js" %}></script>

core/templates/core/partials/scripts2.html
{% load static %}

<!-- App js-->
<script src={% static "/js/script.js" %}></script>

core/templates/core/partials/scriptsAuth.html
{% load static %}
<!-- latest jquery-->
<script src={% static "/js/jquery-3.6.3.min.js" %}></script>

<!-- Bootstrap js-->
<script src={% static "/vendor/bootstrap/bootstrap.bundle.min.js" %}></script>